@startuml domain-model

entity ゆうパック {
    荷物
    個数
    差出地
    宛先地
}

class ゆうパック送料計算サービス {
    基本運賃の計算(都道府県, 都道府県, 荷物, 個数): 料金
    受付可能な荷物か(荷物): 真偽値
}

class 料金 <<値オブジェクト>> {
    本体価格
    消費税
    消費税率
}

class 消費税サービス {
    料金取得(本体価格, 消費税): 料金
    料金取得(本体価格, 消費税率): 料金
}

class 荷物 {
    縦
    横
    高さ
    重さ
    サイズ取得(): サイズ
}

class サイズ <<値オブジェクト>> {
    サイズ名
    荷物の大きさ
}

class 受付可能な荷物

note "縦・横・高さの合計が170cm以下\n重さが25kg以下" as 荷物仕様

class 都道府県 <<値オブジェクト>> {
    都道府県名
    地域名取得(): 地域名
}

enum 地域名 {
    北海道
    東北
    関東
    東京
    信越
    北陸
    東海
    近畿
    中国
    四国
    九州
    沖縄
}

ゆうパック送料計算サービス <.. ゆうパック
ゆうパック "1" *- "1" 荷物 : 100個まで指定可能
荷物 <.. サイズ
ゆうパック .. 受付可能な荷物
受付可能な荷物 <- 荷物仕様
受付可能な荷物 .. 荷物
ゆうパック "1" *- "1" 都道府県 : 差出地
ゆうパック "1" *- "1" 都道府県 : 宛先地
都道府県 -- 地域名
消費税サービス <.. 料金

@enduml
